services:
  service1:
    build: 
      context: ./service1
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./service1/main.py:/app/main.py
      - ./shared_data:/app/shared_data
    environment:
      - SERVICE_NAME=service1
      - SERVICE_VERSION=1.0.0
      - OTHER_SERVICE_URL=http://service2:8002
    depends_on:
      - service2
    networks:
      - microservices-network

  service2:
    build:
      context: ./service2
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./service2/main.py:/app/main.py
      - ./shared_data:/app/shared_data
    environment:
      - SERVICE_NAME=service2
      - SERVICE_VERSION=2.0.0
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  shared_data:
