services:
  service1:
    build: 
      context: ./service1
      dockerfile: Dockerfile.debug
    ports:
      - "8001:8001"
      - "5678:5678"  # Debug port for service1
    volumes:
      - ./shared_data:/app/shared_data
      - ./service1:/app  # Mount source code for live debugging
    environment:
      - SERVICE_NAME=service1
      - SERVICE_VERSION=1.0.0
      - OTHER_SERVICE_URL=http://service2:8002
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    depends_on:
      - service2
    networks:
      - microservices-network
    stdin_open: true
    tty: true

  service2:
    build:
      context: ./service2
      dockerfile: Dockerfile.debug
    ports:
      - "8002:8002"
      - "5679:5679"  # Debug port for service2
    volumes:
      - ./shared_data:/app/shared_data
      - ./service2:/app  # Mount source code for live debugging
    environment:
      - SERVICE_NAME=service2
      - SERVICE_VERSION=2.0.0
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    networks:
      - microservices-network
    stdin_open: true
    tty: true

networks:
  microservices-network:
    driver: bridge

volumes:
  shared_data:
